[tox]
no_package = True
skip_missing_interpreters = True
env_list = format, lint, unit
min_version = 4.0.0

[vars]
src_path = {tox_root}/src
tests_path = {tox_root}/tests
all_path = {[vars]src_path} {[vars]tests_path}
uv_flags = --isolated

[testenv]
allowlist_externals = uv
basepython = python3
set_env =
    PYTHONPATH = {tox_root}:{[vars]src_path}
    PYTHONBREAKPOINT=pdb.set_trace
    PY_COLORS=1
pass_env = PYTHONPATH, CHARM_BUILD_DIR, MODEL_SETTINGS

[testenv:format]
commands =
    uv tool run {[vars]uv_flags} ruff format {[vars]all_path}
    uv tool run {[vars]uv_flags} ruff check --fix {[vars]all_path}

[testenv:lint]
commands =
    uv sync --active --group lint
    uv tool run {[vars]uv_flags} codespell {tox_root}
    uv tool run {[vars]uv_flags} ruff check {[vars]all_path}

[testenv:unit]
commands =
    uv sync --active --group unit
    uv run coverage run --source={[vars]src_path} --module pytest \
        {[vars]tests_path}/unit {posargs}
    uv tool run {[vars]uv_flags} coverage report
