name: Promote charm

on:
  workflow_dispatch:
    inputs:
      origin-channel:
        description: Origin channel
        required: true
        default: 2.10/edge
      destination-channel:
        description: Destination channel
        required: true
        default: 2.10/beta

concurrency:
  group: promote-${{ github.ref }}
  cancel-in-progress: true

jobs:
  promote:
    name: Promote charm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Promote charm
        uses: canonical/charming-actions/release-charm@2.7.0
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          origin-channel: ${{ inputs.origin-channel }}
          destination-channel: ${{ inputs.destination-channel }}
          tag-prefix: nifi
          charmcraft-channel: 4.x/stable
