name: Tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo snap install astral-uv --classic
          uv tool install tox

          sudo snap install just --classic

      - name: Run lint
        run: just lint

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo snap install astral-uv --classic
          uv tool install tox

          sudo snap install just --classic

      - name: Run unit tests
        run: just unit

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get purge $(dpkg -l | grep -i docker | awk '{print $2}')
          sudo apt-get purge containerd.io
          sudo rm -r /run/containerd

          sudo snap install concierge --classic

          sudo snap install just --classic

          sudo -E concierge prepare -p k8s --extra-snaps=astral-uv

          sudo k8s kubectl config view --raw > ~/.kube/config

          uv tool install tox

      - name: Run integration tests
        run: just integration

      - name: Get system state (if failure)
        if: failure()
        run: just get-system-state